title: tayfun kalaycı
description: >-
  Gün içerisinde kafamın içinde birbirini tekrarlayan fikirler için bir yuva.
linkedin_url: "https://www.linkedin.com/in/tayfun-kalayci-7b5a18161/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kalaycitayfun.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
